[package]
name = "flarb"
version = "0.1.0"
edition = "2021"
authors = ["brahman"]
description = "High Performance MEV Bot"
repository = "https://github.com/Panda404NotFound"

[workspace]
members = ["."]

[lib]
path = "src/lib.rs"

[package.metadata.membership]
include = ["**/*.rs"]
auto-export = true

[dependencies]
helius = "0.2.2"
jup-ag = { version = "0.8.0" }
tokio = { version = "1.36.0", features = ["full"] }